apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_KEY: YXNkZg==


# The type: Opaque indicates a generic secret.
# The value YXNkZg== is the base64 encoded version of "asdf". In a declarative format, secret values must be base64 encoded.
# To base64 encode a value, you can use:

# On Linux/macOS: echo -n "asdf" | base64